<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>test.kuz.mobi - <?php if (!empty($title)) echo $title ?> </title>
        <meta content="IE=edge" http-equiv="X-UA-Compatible" />       

        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
        <link rel="stylesheet" href="/css/uploadify.css" />
        <link rel="stylesheet" href="/css/main.css" />
        <link rel="stylesheet" href="/css/admin.css" />

        <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
        <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script> 
        <script src="/js/adm.js"></script> 

        <!--[if lte IE 9]>        
        <link href="/css/ie8.css" rel="stylesheet" type="text/css" />
        <script src="/js/ie8.js"></script>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>        
        <![endif]-->
    </head>

    <body>
        <header>
            <div id="logo"></div>
            <h1>
                <?php if (!empty($title)) echo $title ?>                   
            </h1>
            <?php if (!empty($_SESSION['admin_login'])): ?>

                <nav>
                    <?php if (empty($page) || $page != 'adminindex'): ?>
                        <a href="/admin/">Админка</a>
                    <?php endif; ?>

                    <?php if (!empty($page) && $page != 'adminusers'): ?>
                        <a href="/admin/users/">Пользователи</a>
                    <?php endif; ?>


                    <a href="/admin/logout/">Logout <?= $_SESSION['admin_login'] ?></a>

                </nav>

            <?php endif; ?>
        </header>