<main>
    <article>
        <div class="form admin">
            <form id="login_form" method="post">
                <fieldset>
                    <legend>Логин/пароль</legend> 
                    <p id="error"></p>
                    <input id="login" name="login" type="text" placeholder="Логин" required />
                    <input id="password" name="password" type="password" placeholder="Пароль" required />
                </fieldset>
                 <p class="clr"></p>
                <button class="button" id="login_button">Продолжить</button>
            </form>
        </div>
    </article>
</main>