<main>
    <article>
        <h2>Lorem ipsum dolor sit amet</h2>
        <p>Ut nec feugiat quam. Quisque eget suscipit nulla, id dignissim nunc. 
            In hac habitasse platea dictumst. Sed ullamcorper pharetra augue,
            quis vestibulum odio varius molestie. Vivamus fermentum volutpat 
            nisi ac faucibus. Aenean ut facilisis dolor, a tincidunt tellus. 
            Proin quis sem ac nisi eleifend dictum. Nullam magna velit, dictum 
            sit amet lorem quis, sodales malesuada ex. Vivamus rutrum elit quis 
            lectus eleifend interdum iaculis ut massa. Nulla varius condimentum 
            mauris, ut interdum ex imperdiet ut. Maecenas iaculis tellus ligula,
            eu ornare dolor rhoncus ac. Nulla molestie metus eu tempus porta. 
            Aenean sodales arcu sit amet nibh dignissim feugiat.</p>

        <aside>
            <h4>"Curabitur imperdiet"</h4>
            <p>Nam varius eros quis fermentum semper. Nam vehicula, 
                dolor vitae cursus porta, neque sem iaculis justo, sit amet 
                hendrerit sem enim at dolor. Sed vitae bibendum sem. Duis varius
                ligula eu eros sollicitudin, at dapibus elit placerat.</p>
        </aside>

        <section>
            <h3>Fusce tristique efficitur metus ut luctus</h3>
            <p>In egestas, metus in rhoncus ullamcorper, ligula augue tincidunt
                lorem, at tempus est augue sed ipsum. Pellentesque sed hendrerit
                eros, ut pulvinar felis. Ut quis metus ac tellus dapibus ullamcorper.
                Etiam lacus ex, ornare quis felis non, condimentum luctus nibh. 
                Nam tincidunt scelerisque massa placerat consectetur. 
                Proin vitae felis quis sem egestas vehicula vitae eget arcu. 
                Pellentesque habitant morbi tristique senectus et netus et malesuada 
                fames ac turpis egestas. Donec ut erat nisl. Aliquam fringilla egestas
                neque id congue. Maecenas sollicitudin lobortis facilisis</p>
        </section>

       
    </article>
</main>